using System;
using Npgsql;

namespace DataAccessLayer
{
    public static class DatabaseInitializer
    {
        public static void Initialize()
        {
            var dbConnection = new DbConnection();

            using NpgsqlConnection conn = dbConnection.GetConnection();
            conn.Open();

            const string createUsersTable = @"
                CREATE TABLE IF NOT EXISTS Users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(150) NOT NULL,
                    phone VARCHAR(20) NOT NULL
                );";

            const string createNotificationsTable = @"
                CREATE TABLE IF NOT EXISTS Notifications (
                    notificationid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    userid INT NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
                    message TEXT NOT NULL,
                    type VARCHAR(50) NOT NULL,
                    sentdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                );";

            const string createUserEmailIndex = @"
                CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON Users(LOWER(email));";

            const string createNotificationUserIndex = @"
                CREATE INDEX IF NOT EXISTS idx_notifications_userid ON Notifications(userid);";

            using var cmd = conn.CreateCommand();
            cmd.CommandText = string.Join(Environment.NewLine, new[]
            {
                createUsersTable,
                createNotificationsTable,
                createUserEmailIndex,
                createNotificationUserIndex
            });
            cmd.ExecuteNonQuery();
        }
    }
}
